//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTestFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int id { get; set; }
        public Nullable<int> recipe_id { get; set; }
        public Nullable<int> Antall { get; set; }
        public string Navn { get; set; }
    
        public virtual Oppskrift Oppskrift { get; set; }
    }
}
