//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTestFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oppskrift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oppskrift()
        {
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int id { get; set; }
        public string Tittel { get; set; }
        public string Innhold { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public byte[] Bilde { get; set; }
        public Nullable<int> Gruppe { get; set; }
        public Nullable<bool> Publisert { get; set; }
    
        public virtual Grupper Grupper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
